### ISSUE TITLE
Example request: FreeRTOS+Low Power+LoRaWAN

### ISSUE THREAD

**Issue by jpmeijers** [stm32duino/STM32LoRaWAN#19]
My ideal setup would be an STM32 running FreeRTOS, going into Low Power mode in its idle task, periodically sending LoRa packets from a FreeRTOS task.

Basically I would need to combine these three libraries:
* https://github.com/stm32duino/STM32LoRaWAN
* https://github.com/stm32duino/STM32FreeRTOS
* https://github.com/stm32duino/STM32LowPower

Currently this is not possible. The first hurdle to overcome is issue #9. After that one would need to combine LowPower with FreeRTOS. I also imagine one would need to replace the LoRaWAN internal scheduler with FreeRTOS.

**Comment by fpistm** [comment]
Hi @jpmeijers 

STM32FreeRTOS is provided "as is" and is up to end user to configure and use it. So no example using is planned.
About LowPower, #9 already exists to track this.
