### ISSUE TITLE
LoRaWAN Issue on RAK3172

### ISSUE THREAD

**Issue by HelgeSeidel** [stm32duino/STM32LoRaWAN#31]
Trying to run the LoRaWAN Basic example on my RAK3172 with STM32LoRaWAN library v0.1.1. Similar to https://github.com/stm32duino/STM32LoRaWAN/issues/24 I get the Message:

Start
Error\Arduino\libraries\STM32LoRaWAN\src\BSP\rtc.c (56)

**Comment by fpistm** [comment]
Probably issue with LSE of the RAK. You should try to debug to see  what happen. Soon RTC will be managed by the STM32RTC library.

**Comment by HelgeSeidel** [comment]
I will spend some time debugging as soon as my new development board arrived.

**Comment by fpistm** [comment]
Hi @HelgeSeidel 
Could you retry with the latest verison of the library, as now the RTC is managed by the STM32RTC https://github.com/stm32duino/STM32RTC/releases/tag/1.4.0

I close this one as you could not have the same error with the 0.2.0 version of the library.

**Comment by HelgeSeidel** [comment]
Hi @fpistm , I used the latest release for my project today. 

👍🏼👍🏼👍🏼
